### ISSUE TITLE
Overall code style

### ISSUE THREAD

**Issue by Mironor** [scaldi/scaldi#56]
So I was looking through the code and saw some lines like:

```
  protected def initEagerWordBindings(lifecycleManager: LifecycleManager): () => Unit =
    wordBindings |> (b => () => b.filter(_.isEager).foreach(_ get lifecycleManager))
```

It took me some time to understand what's going on and I'm far from novice in Scala.

So is this code equivalent to

```
() => wordBindings.filter(_.isEager).foreach(_.get(LifecycleManager))
```

If so, why complexify it? And if I didn't understand it right, could we consider simplification of some parts like this one?

Also what scala style do you use? There is a great variety of them from classic http://docs.scala-lang.org/style/ to more java-like https://github.com/databricks/scala-style-guide

**Comment by OlegIlyenko** [comment]
You are right. In this case `|>` is not really necessary or helpful, as you said, it just complicates things here. In general I like to use `|>`, Once I even written a blog post about it :)

http://hacking-scala.org/post/49046871971/inverting-the-flow-of-your-code

About the infix notation (`_ get lifecycleManager` vs `_.get(lifecycleManager)`). I personally prefer to use it where possible and where it looks good, I find that it make the syntax much more lightweight and easier to read. Funny enough, my colleges also sometimes complain about this preference of mine :D But in the end we normally reach a consensus by defining API where we all agree to use infix notation.

About the coding style... It's roughly normal scala style guide, but I normally don't follow it religiously. I think it's ok to do something a little bit different if there is a reason for it, like for example it makes code more readable, or makes it easier to express the intent.

In general I prefer to rely more on the code reviews and communication rather than some set of generic rules (don't get me wrong, I think they still can be helpful but more as a guideline rather than a rule).

**Comment by Mironor** [comment]
Great, thanks for your reply, I will use this issue when I need some help with understanding the code.
