### ISSUE TITLE
cannot use scaldi-akka and get an injected router

### ISSUE THREAD

**Issue by yaneeves** [scaldi/scaldi#58]
It seems as if there is no built in way to pass on a Props instance to scaldi-akka's AkkaInjectable.

That being the case, in case I wish to use a router it seems as if the following is my only recourse:

```
import scaldi.akka.AkkaInjectable._

class ActorModule extends Module {
  implicit val system = ActorSystem("some-system")

  bind[ActorSystem] to system destroyWith (_.shutdown())

  private val router = system.actorOf(FromConfig.props(), "a-router") 
  binding identifiedBy 'arouter to router


  binding toProvider new ARoutee
  binding identifiedBy 'aRoutee to injectActorRef[ARoutee](name = "a-routee")

  
}
```

and

```
akka.actor.deployment {
      /a-router {
        router = round-robin-group
        routees.paths = ["/user/a-routee"]


      }
```

**Comment by OlegIlyenko** [comment]
You can use `injectActorProps` which will inject `Props[ARoutee]`:

http://scaldi.org/learn/#akka-integration

also I noticed that you are defining `val`s inside of a module. i would discourage thi since `val`s are eager and `Module` has it's own lifecycle and initialization, which happens after module was instantiated. In your case i would suggest to do something like this:

```scala
bind [ActorSystem] to ActorSystem("some-system") destroyWith (_.shutdown())

binding identifiedBy 'arouter to {
  implicit val system = inject [ActorSystem]

  system.actorOf(FromConfig.props(AkkaInjectable.injectActorProps[ARoutee]), "a-router")
}

**Comment by yaneeves** [comment]
Thanks, will take the `val` comment into account.
Yet, the `FromConfig.props(routeeProps: Props)` method is for a pool of routees not for a group as in my example

**Comment by OlegIlyenko** [comment]
Indeed, sorry I haven't noticed that you are using group. Do you inject `binding identifiedBy 'aRoutee to injectActorRef[ARoutee](name = "a-routee")` somewhere else in the code? Since binding is lazy (by default), routee actor will not be created if not injected somewhere. If that's the case, than you can bind it with `toNonLazy` instead of `to`. This will ensure it's creation during the startup.

Also in you example you are creating routee actor directly from the `system`, which would mean that it's path will not contain a `user`, as defined in the configuration. Or do I miss something?

**Comment by yaneeves** [comment]
Thanks again for the tip.
I changed the following (after your initial tip):

```
binding identifiedBy 'aRouter to {
    implicit val system = inject [ActorSystem]

    val aRoutee = inject[ActorRef]('aRoutee)
    system.actorOf(FromConfig.props(), "a-router")
  }

  binding toProvider new ARoutee
  binding identifiedBy 'aRoutee to {
    injectActorRef[ARoutee](name = "a-routee")
  }


```
to this 

```
binding identifiedBy 'aRouter to {
    implicit val system = inject [ActorSystem]

    system.actorOf(FromConfig.props(), "a-router")
  }

  binding toProvider new ARoutee
  binding identifiedBy 'aRoutee toNonLazy
    injectActorRef[ARoutee](name = "a-routee")

```
And this seems to do the job as well.


As per the `system` any actor created directly under the system is created under the user guardian (http://doc.akka.io/docs/akka/snapshot/general/supervision.html#The_Top-Level_Supervisors) and so the /user prefix in the configuration is mandatory (and anyway is works ;-))


Also, please, is there a solution regarding the router group?

**Comment by OlegIlyenko** [comment]
If I understand your issue correctly, you were unable to inject `aRouter`. I think now you should be able to `inject [ActorRef] ('aRouter)`. Or have I misunderstood issue, that you are currently facing?

**Comment by yaneeves** [comment]
What I had wanted, originally, is not to have to invoke system.actorOf explicitly. I can and am injecting `'aRouter` as you have specified above. I guess there is now way to achieve what I want, currently.

**Comment by OlegIlyenko** [comment]
In case of `a-router` actor you need to explicitly create it with `actorFactory.actorOf`. To my knowledge the is no way around it. That said, if you know a way how this could be done in more implicit way, I would be definitely interested to know it.

**Comment by yaneeves** [comment]
I am no scala expert and maybe I am missing something, but a suggestion would be to enhance the current `AkkaInjectable` trait and add a parameter set that takes a `Props` instance and uses that instead of invoking the internal `injectActorProps`

something like:
```
protected def injectActorRef[T](props: Props)(name: String)
                                 (implicit f: ActorRefFactory): ActorRef =
    f.actorOf(props, name)
```

this may not add much in the way of DI but looks a little more uniform IMO...

your thoughts?

**Comment by OlegIlyenko** [comment]
I see, indeed in may add a bit of convenience. I also a bit concerned about adding this kind of feature. I feel that it can cause a confusion do many users, since (IMHO) they naturally expect all these `inject*` functions to inject bindings that were defined in the `Module` in some way. If we decide to introduce such method, I would definitely give it a difference, since inject methods already have very specific semantics associated with them. 

I always tried to keep library very minimalistic and addition of such an unrelated function will unnecessary broaden he scope it. I think I would prefer to keep the library more focused and provide functionality that provides a bridge between akka and scaldi

**Comment by yaneeves** [comment]
I am not sure the proposed functionality is unrelated, but I will close the issue just the same. It would help me though, if you elaborate on why you feel it is unrelated

**Comment by OlegIlyenko** [comment]
I called it unrelated mostly because I see it (please correct me if I'm wrong) as a pure Akka helper function. It does not provide any scaldi-related functionality or functionality related to scaldi-akka integration. Or did I just misunderstood the suggestion?
